### ISSUE TITLE
HMAC IntegrityPack failure

### ISSUE THREAD

**Issue by broganross** [cinecert/asdcplib#4]
Found what appears to be an issue.

Wrap some SMPTE xml into an encrypted mxf:

>asdcp-wrap -j 4fe83eac-8834-4653-89c3-b0abcf167c6f -k 3ee9b974d3dcfd5d042f06d879d71fba source/source.xml out.mxf

Unwrap the MXF with 'verify HMAC' option

>asdcp-unwrap -m -k 3ee9b974d3dcfd5d042f06d879d71fba out.mxf out/test

which causes:

> IntegrityPack failure: sequence is 2, expecting 3.
Program stopped on error.
HMAC authentication failure.

Disabling the '-m' option works fine.

**Comment by dcbullock** [comment]
Fixed in 5000f66.
