### ISSUE TITLE
General Parsing Crashes

### ISSUE THREAD

**Issue by kblinova** [cinecert/asdcplib#5]
Hi, we are implementing IMF IAB support in asdcp library and we ran American Fuzzy Lop on our parser that includes a version of asdcp. Though our code is based on an older version of the library, I confirmed that the issues we found still exist in later versions of the library.

We identified crashes in these areas:
1. m_RIP.PairArray.front() is referenced in h_02_Reader.cpp and h__Reader.cpp without checking if it's empty.
2. KLVPacket::InitFromBuffer() function can set m_ValueLength to extend past the length of the input buffer causing exceptions during parsing. Some of the places where this is an issue:
 - InterchangeObject::InitFromBuffer
 - Primer::InitFromBuffer
 - RIP::InitFromFile
3. CreateObject function uses exact UL match when looking up Factory methods. But GetMDObjectByType ignores UL index 7 when performing comparison (see UL::operator==). This causes a crash in InitInfo() when we perform static cast in order to call MD_to_WriterInfo().

I am not too savvy with git to know how to create a branch in which I can submit the fixes to the above issues.  

Please let me know if you would like me to do that.

**Comment by kblinova** [comment]
I created a repository kblinova/asdcplib where I submitted the fixes to the issues listed above.

**Comment by dcbullock** [comment]
@kblinova I think you want to make a fork of cinecert/asdcplib, commit your changes to your fork and then create a Pull Request.  The default Pull Request will offer to create the request from your fork back to the cinecert/asdcplib repo.  Since you already have a repo, you can very likely make a Pull Request from your repo and fill in the cinecert/ascplib as the base.

**Comment by dcbullock** [comment]
@kblinova And thanks for working on the library!

**Comment by kblinova** [comment]
Hey Dean, I will try that, thanks!

**Comment by kblinova** [comment]
Hey Dean, I created a branch with my fixes on my local machine, but I cannot push my branch to this repository. I don't have a permission to do that.  I don't think anyone external can create branches on this repository.

**Comment by kblinova** [comment]
Finally created a pull request.
