### ISSUE TITLE
IMF_IABEssenceClipWrappedElement UL value is incorrect in written IMF MXF files.

### ISSUE THREAD

**Issue by kblinova** [cinecert/asdcplib#59]
The value of IMF_IABEssenceClipWrappedElement UL should be 060e2b34.01020101.0d010301.16**01**0d**01** after it is written to the MXF file. 

The value ends up being 060e2b34.01020101.0d010301.16**7f**0d**7f**

**Comment by palemieux** [comment]
@kblinova See #64
